version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # Map port 3000 on the host to port 80 in the container
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"  # Map port 5000 on the host to port 5000 in the container
    volumes:
      - ./backend/database.json:/app/database.json
    networks:
      - internal

networks:
  internal:
    driver: bridge
